- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: Copy application to /app
  ansible.posix.synchronize:
    src: ../app
    dest: /

- name: Install Symfony dependencies
  community.general.composer:
    command: require
    arguments: symfony/requirements-checker
    classmap_authoritative: true
    no_dev: true
    working_dir: /app

- name: Clear Symfony cache
  ansible.builtin.shell: php bin/console cache:clear
  args:
    chdir: /app
  environment:
    APP_ENV: prod
    APP_DEBUG: '0'

- name: Remove default nginx site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Install CyberMatos site configuration
  template: src=cybermatos.tech.conf.j2 dest=/etc/nginx/sites-enabled/cybermatos.tech.conf mode=0644
  become: true

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: yes
  become: true
