---
- hosts: all
  name: Deploy CyberMatos
  roles:
    # Perform all the basic setup (packages, services, etc.) as root by default
    - role: base_install
      become: true
    # Deploy the application as the regular user by default
    - role: deploy_application
