name: Main

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: shivammathur/setup-php@2.25.0
      with:
        php-version: '8.2'
        coverage: none

    - name: Install PHP CS Fixer
      working-directory: app
      run: composer require --dev --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer

    - name: Run Formatter
      working-directory: app
      run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix

    - name: Check Formatting
      run: |
        git -c core.fileMode=false diff --output /tmp/formatting-diff
        if [ -s /tmp/formatting-diff ]; then
          echo "Found formatting differences, please run 'tools/php-cs-fixer/vendor/bin/php-cs-fixer fix' in the app directory and commit the changes"
          cat /tmp/formatting-diff
          exit 1
        fi
        echo "Code is formatted correctly"
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@2.25.0
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Create Test Database
        working-directory: app
        run: |
          composer install
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:create --env=test
      
      - name: Run Tests
        working-directory: app
        run: ./bin/phpunit --coverage-clover ./coverage.xml

      - name: Upload Coverage Data
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/coverage.xml
