# Mirrors the commits of this repo to the Epitech repo
name: Mirroring

on:
  push:
    branches:
      - master

jobs:
  to_epitech_github:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch depth set to 0 means that all commits are to be mirrored

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:EpitechMscProPromo2025/T-WEB-600-NAN-6-1-ecommerce-yanis.guaye.git
        ssh_private_key:
          ${{secrets.EPITECH_MIRROR_SSH_KEY}}
